package hashtable;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

        hashTable test = new hashTable(10);

        test.add("test","test 1");
        assertEquals(true ,test.contains("test"));

        assertEquals("test 1",test.get("test"));
        assertEquals("invalid key",test.get("test4"));

        test.add("a","aaa");
        test.add(2,"two");
        assertEquals("aaa",test.get("a"));
        assertEquals("two",test.get(2));
        assertEquals(9,test.hashTableStringKey ("hi"));
    }
    
}
