package hashtable;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

        hashTable test = new hashTable(10);

        test.add("test","test 1");
        assertEquals(true ,test.contains("test"));

        assertEquals("test 1",test.get("test"));
        assertEquals("invalid key",test.get("test4"));

        test.add("a","aaa");
        test.add(2,"two");
        assertEquals("aaa",test.get("a"));
        assertEquals("two",test.get(2));
        assertEquals(9,test.hashTableStringKey ("hi"));
    }
    @Test void firstRepeatedWord() throws Exception{
        hashTable hashMap= new hashTable(7);
        assertEquals("a", hashMap.repeatedWord("Once upon a time, there was a brave princess who..."));
}
@Test void leftFunction(){
    Map<String,String> mapOne=new HashMap<>();
    Map<String,String> mapTwo=new HashMap<>();

    mapOne.put("fond","enamored");
    mapOne.put("wrath","anger");
    mapOne.put("diligent","employed");
    mapOne.put("outfit","garb");
    mapOne.put("guide","usher");

    mapTwo.put("fond","averse");
    mapTwo.put("wrath","delight");
    mapTwo.put("diligent","idle");
    mapTwo.put("guide","follow");
    mapTwo.put("flow","jam");


    assertEquals("{diligent=[employed, null], outfit=[garb, null], wrath=[anger, null], guide=[usher, null], fond=[enamored, null]}",App.leftJoins(mapOne,mapTwo).toString());
}
}