package hashtable;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        hashTable HashTable = new hashTable(7);
        HashTable.add(0,"test add method");
        System.out.println(HashTable.get(0));
        System.out.println(HashTable.contains(0));
        HashTable.add(1,"test 2");
        System.out.println(HashTable.get(1));
        System.out.println(HashTable.contains(1));
        System.out.println(HashTable.get(2));
        System.out.println(HashTable.contains(2));

        HashTable.add("t","tt");
        System.out.println(HashTable.get("t"));
        System.out.println("**********************");
        String x="\"Once upon a time, there was a brave princess who...\"";

        System.out.println("**********************");


    }
}
